global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: azure-apps
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - replace-dev-web.azurewebsites.net
          - replace-dev-api.azurewebsites.net
          - replace-qa-web.azurewebsites.net
          - replace-qa-api.azurewebsites.net
          - replace-prod-web.azurewebsites.net
          - replace-prod-api.azurewebsites.net
