- targets:
    - https://app-agentice2e-dev-web-ivvfqo.azurewebsites.net/health
  labels:
    environment: dev
    app: web
- targets:
    - https://app-agentice2e-dev-api-ivvfqo.azurewebsites.net/health
  labels:
    environment: dev
    app: api
- targets:
    - https://app-agentice2e-qa-web-247qqa.azurewebsites.net/health
  labels:
    environment: qa
    app: web
- targets:
    - https://app-agentice2e-qa-api-247qqa.azurewebsites.net/health
  labels:
    environment: qa
    app: api
- targets:
    - https://app-agentice2e-prod-web-ciabpr.azurewebsites.net/health
  labels:
    environment: prod
    app: web
- targets:
    - https://app-agentice2e-prod-api-ciabpr.azurewebsites.net/health
  labels:
    environment: prod
    app: api
