- targets:
    - http://site.dev.sdd.localhost/health
  labels:
    environment: dev
    app: site
    provider: rancher-desktop
- targets:
    - http://api.dev.sdd.localhost/health
  labels:
    environment: dev
    app: api
    provider: rancher-desktop
- targets:
    - http://site.qa.sdd.localhost/health
  labels:
    environment: qa
    app: site
    provider: rancher-desktop
- targets:
    - http://api.qa.sdd.localhost/health
  labels:
    environment: qa
    app: api
    provider: rancher-desktop
- targets:
    - http://site.prod.sdd.localhost/health
  labels:
    environment: prod
    app: site
    provider: rancher-desktop
- targets:
    - http://api.prod.sdd.localhost/health
  labels:
    environment: prod
    app: api
    provider: rancher-desktop
