apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Infinity Health
    type: yesoreyeram-infinity-datasource
    uid: infinity-health
    access: proxy
    editable: true
    jsonData:
      allowedHosts:
        - http://health-probe:8090
        - http://host.docker.internal:8088
        - http://host.docker.internal:3000
        - http://host.docker.internal:5001
        - http://host.docker.internal:8081
        - http://host.docker.internal:8082
        - http://host.docker.internal:8083
        - http://host.docker.internal:5002
        - http://host.docker.internal:5003
        - http://host.docker.internal:5004
        - http://sdd-cluster-control-plane:30080
        - http://sdd-cluster-control-plane:30500
        - http://sdd-cluster-control-plane:31080
        - http://sdd-cluster-control-plane:31500
        - http://sdd-cluster-control-plane:32080
        - http://sdd-cluster-control-plane:32500
        - http://localhost:30080
        - http://localhost:30500
        - http://localhost:31080
        - http://localhost:31500
        - http://localhost:32080
        - http://localhost:32500
